version: "3.9"
services:
  mlflow:
    build: .
    environment:
      - BACKEND_STORE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432
    ports:
      - "${MLFLOW_PORT}:5000"
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_volume:/var/lib/postgresql/data/
volumes:
  mlflow_volume:
  postgres_volume: