version: "3.9"
services:
  mlflow:
    build:
      context: .
      args:
        - BACKEND_STORE_URI='postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:${POSTGRES_PORT}'
        - MLFLOW_PORT=${MLFLOW_PORT}
    ports:
      - "${MLFLOW_PORT}:${MLFLOW_PORT}"
    volumes:
      - mlflow_volume:/mlflow/
  db:
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_volume:/var/lib/postgresql/data
volumes:
  mlflow_volume:
  postgres_volume: